import discord
from discord.ext import commands
from discord import app_commands
import sqlite3
import io
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

class TranscriptCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        
    @app_commands.command(name='transcript', description='Generate a transcript of the current ticket')
    async def transcript(self, interaction: discord.Interaction):
        """Generate a transcript of the current ticket"""
        # Check if this is a ticket channel
        if not interaction.channel.name.startswith('ticket-'):
            embed = discord.Embed(
                title="❌ Not a Ticket Channel",
                description="This command can only be used in ticket channels.",
                color=discord.Color.red()
            )
            await interaction.response.send_message(embed=embed, ephemeral=True)
            return
        
        # Check permissions
        if not (await self.check_ticket_permissions(interaction.user, interaction.guild) or
                await self.is_ticket_owner(interaction.user.id, interaction.channel.id)):
            embed = discord.Embed(
                title="❌ Permission Denied",
                description="You don't have permission to generate transcripts.",
                color=discord.Color.red()
            )
            await interaction.response.send_message(embed=embed, ephemeral=True)
            return
        
        await interaction.response.defer()
        
        # Get ticket info
        ticket_info = await self.get_ticket_info(interaction.channel.id)
        if not ticket_info:
            embed = discord.Embed(
                title="❌ Ticket Not Found",
                description="Could not find ticket information in the database.",
                color=discord.Color.red()
            )
            await interaction.followup.send(embed=embed, ephemeral=True)
            return
        
        # Generate transcript
        transcript = await self.generate_transcript(interaction.channel, ticket_info)
        
        # Create file
        file_content = transcript.encode('utf-8')
        file = discord.File(
            io.BytesIO(file_content),
            filename=f"ticket-{ticket_info['ticket_number']:04d}-transcript.txt"
        )
        
        # Send transcript
        embed = discord.Embed(
            title="📄 Ticket Transcript Generated",
            description=f"Transcript for ticket #{ticket_info['ticket_number']:04d}",
            color=discord.Color.green(),
            timestamp=datetime.utcnow()
        )
        embed.add_field(name="Channel", value=interaction.channel.mention, inline=True)
        embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
        
        await interaction.followup.send(embed=embed, file=file)
        
        logger.info(f"Transcript generated for ticket #{ticket_info['ticket_number']:04d} by {interaction.user}")
    
    async def generate_transcript(self, channel, ticket_info):
        """Generate a text transcript of the ticket"""
        transcript = []
        
        # Header
        transcript.append("=" * 60)
        transcript.append(f"TICKET TRANSCRIPT - #{ticket_info['ticket_number']:04d}")
        transcript.append("=" * 60)
        transcript.append("")
        
        # Ticket info
        transcript.append(f"Subject: {ticket_info['subject']}")
        transcript.append(f"Created by: {ticket_info['user_id']}")
        transcript.append(f"Created at: {ticket_info['created_at']}")
        transcript.append(f"Status: {ticket_info['status']}")
        transcript.append(f"Channel: #{channel.name}")
        transcript.append("")
        transcript.append(f"Description: {ticket_info['description']}")
        transcript.append("")
        transcript.append("-" * 60)
        transcript.append("MESSAGES")
        transcript.append("-" * 60)
        transcript.append("")
        
        # Get all messages
        messages = []
        async for message in channel.history(limit=None, oldest_first=True):
            if not message.author.bot or message.embeds or message.attachments:
                messages.append(message)
        
        # Add messages to transcript
        for message in messages:
            timestamp = message.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            author = f"{message.author.display_name} ({message.author})"
            
            transcript.append(f"[{timestamp}] {author}:")
            
            if message.content:
                # Add message content with proper indentation
                for line in message.content.split('\n'):
                    transcript.append(f"  {line}")
            
            # Add embeds
            if message.embeds:
                for embed in message.embeds:
                    transcript.append("  [EMBED]")
                    if embed.title:
                        transcript.append(f"    Title: {embed.title}")
                    if embed.description:
                        transcript.append(f"    Description: {embed.description}")
                    if embed.fields:
                        for field in embed.fields:
                            transcript.append(f"    {field.name}: {field.value}")
            
            # Add attachments
            if message.attachments:
                for attachment in message.attachments:
                    transcript.append(f"  [ATTACHMENT] {attachment.filename} ({attachment.url})")
            
            transcript.append("")
        
        # Footer
        transcript.append("-" * 60)
        transcript.append(f"Transcript generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
        transcript.append(f"Total messages: {len(messages)}")
        transcript.append("=" * 60)
        
        return '\n'.join(transcript)
    
    async def is_ticket_owner(self, user_id, channel_id):
        """Check if user is the ticket owner"""
        conn = sqlite3.connect(self.bot.db_path)
        cursor = conn.cursor()
        cursor.execute('SELECT user_id FROM tickets WHERE channel_id = ?', (channel_id,))
        result = cursor.fetchone()
        conn.close()
        
        return result and result[0] == user_id
    
    async def get_ticket_info(self, channel_id):
        """Get ticket information from database"""
        conn = sqlite3.connect(self.bot.db_path)
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM tickets WHERE channel_id = ?', (channel_id,))
        result = cursor.fetchone()
        conn.close()
        
        if result:
            return {
                'user_id': result[3],
                'ticket_number': result[4],
                'subject': result[5],
                'description': result[6],
                'status': result[7],
                'created_at': result[8]
            }
        return None
    
    async def check_ticket_permissions(self, user, guild):
        """Check if user has ticket management permissions"""
        if user.guild_permissions.manage_channels:
            return True
        
        # Check configured support roles
        conn = sqlite3.connect(self.bot.db_path)
        cursor = conn.cursor()
        cursor.execute('SELECT ping_roles FROM ticket_config WHERE guild_id = ?', (guild.id,))
        result = cursor.fetchone()
        conn.close()
        
        if result and result[0]:
            role_names = [role.strip() for role in result[0].split(',')]
            for role_name in role_names:
                if discord.utils.get(user.roles, name=role_name):
                    return True
        
        return False

async def setup(bot):
    await bot.add_cog(TranscriptCog(bot))