import nodemailer from 'nodemailer';

interface EmailParams {
  to: string;
  subject: string;
  html: string;
  text?: string;
}

class EmailService {
  private transporter: nodemailer.Transporter | null = null;

  constructor() {
    this.initializeTransporter();
  }

  private initializeTransporter() {
    if (!process.env.GMAIL_APP_PASSWORD) {
      console.warn('Gmail App Password not configured - email notifications disabled');
      return;
    }

    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: 'nexguards@gmail.com',
        pass: process.env.GMAIL_APP_PASSWORD
      }
    });
  }

  async sendEmail(params: EmailParams): Promise<boolean> {
    if (!this.transporter) {
      console.error('Email service not configured');
      return false;
    }

    try {
      const mailOptions = {
        from: 'nexguards@gmail.com',
        to: params.to,
        subject: params.subject,
        html: params.html,
        text: params.text
      };

      const result = await this.transporter.sendMail(mailOptions);
      console.log(`Email sent successfully: ${result.messageId}`);
      return true;
    } catch (error) {
      console.error('Failed to send email:', error);
      return false;
    }
  }

  async sendTestimonialNotification(testimonial: {
    id: number;
    name: string;
    serverName: string;
    rating: number;
    message: string;
    approvalLink: string;
    rejectLink: string;
  }): Promise<boolean> {
    const subject = `🌟 New Testimonial Awaiting Approval from ${testimonial.name}`;
    
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
        <div style="background: linear-gradient(135deg, #06b6d4, #8b5cf6); padding: 30px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 28px;">🌟 New Testimonial Awaiting Approval!</h1>
        </div>
        
        <div style="padding: 30px; background: #f8fafc;">
          <div style="background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #1e293b; margin-top: 0;">Testimonial Details</h2>
            
            <div style="margin: 20px 0;">
              <strong style="color: #475569;">From:</strong> ${testimonial.name}<br>
              <strong style="color: #475569;">Server:</strong> ${testimonial.serverName}
            </div>
            
            <div style="margin: 20px 0;">
              <strong style="color: #475569;">Rating:</strong> 
              <span style="color: #f59e0b; font-size: 18px;">${'⭐'.repeat(testimonial.rating)}</span>
              (${testimonial.rating}/5)
            </div>
            
            <div style="margin: 20px 0;">
              <strong style="color: #475569;">Message:</strong>
              <div style="background: #f1f5f9; padding: 15px; border-radius: 8px; margin-top: 10px; border-left: 4px solid #06b6d4;">
                <p style="margin: 0; color: #334155; line-height: 1.6;">${testimonial.message}</p>
              </div>
            </div>
            
            <div style="margin: 30px 0; text-align: center;">
              <h3 style="color: #1e293b; margin-bottom: 20px;">Take Action:</h3>
              <div style="display: inline-block; margin: 0 10px;">
                <a href="${testimonial.approvalLink}" style="background: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">
                  ✅ APPROVE
                </a>
              </div>
              <div style="display: inline-block; margin: 0 10px;">
                <a href="${testimonial.rejectLink}" style="background: #ef4444; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">
                  ❌ REJECT
                </a>
              </div>
            </div>
            
            <div style="background: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b; margin-top: 20px;">
              <p style="margin: 0; color: #92400e; font-size: 14px;">
                <strong>⚠️ Action Required:</strong> This testimonial will NOT appear on your website until you approve it by clicking the "APPROVE" button above.
              </p>
            </div>
          </div>
        </div>
        
        <div style="background: #1e293b; padding: 20px; text-align: center;">
          <p style="color: #94a3b8; margin: 0; font-size: 14px;">
            This email was automatically generated by the NexGuard website testimonial system.
          </p>
        </div>
      </div>
    `;

    return this.sendEmail({
      to: 'nexguards@gmail.com',
      subject,
      html
    });
  }

  async sendFeedbackNotification(feedback: {
    name: string;
    email?: string;
    type: string;
    message: string;
  }): Promise<boolean> {
    const subject = `New Feedback: ${feedback.type} from ${feedback.name}`;
    
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #00FFFF; border-bottom: 2px solid #00FFFF; padding-bottom: 10px;">
          📝 New NexGuard Feedback
        </h2>
        
        <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #333; margin-top: 0;">Feedback Details</h3>
          <p><strong>Name:</strong> ${feedback.name}</p>
          ${feedback.email ? `<p><strong>Email:</strong> ${feedback.email}</p>` : ''}
          <p><strong>Type:</strong> ${feedback.type}</p>
          
          <div style="margin-top: 20px;">
            <strong>Message:</strong>
            <div style="background: white; padding: 15px; border-left: 4px solid #00FFFF; margin-top: 10px;">
              ${feedback.message}
            </div>
          </div>
        </div>
        
        <p style="color: #666; font-size: 12px;">
          This feedback was submitted through the NexGuard website feedback system.
        </p>
      </div>
    `;

    return this.sendEmail({
      to: 'nexguards@gmail.com',
      subject,
      html
    });
  }
}

export const emailService = new EmailService();